
# Discussion and Conclusion

Childhood is a vital period for the formation of human and social capital and is critical in preparing societies for future prosperity, sustainability, and therefore, children's optimal socio-emotional development is a critical component of a country's sustainable development. Supporting early childhood development strengthens human capital architecture, increases economic performance, fosters community development. Parents are the first and principal individuals entrusted with child care and the primary responsibility of developing children to become competent members of their community worldwide. Children thrive when their families provide cognitive and socio-emotional care, which includes imparting information through tutoring and instilling interpersonal competency through socialization.

This study focused on the association between the caregivers' stimulation activities and child's socio-emotional development in 3-4 years old children in Bangladesh. This study employed a binary logistic regression to assess the effect of caregivers' stimulation on child's development in socio-emotional domain of early childhood development (ECD). Data from the 2019 Bangladesh MICS was analyzed to obtain current status regarding the association between the exposure and the outcome while controlling for possible individual level and community level background characteristics.

## Findings and Discussion

In contrast to conventional perception, this study found that level of caregivers' stimulation, measured by the number of different kinds of activities performed with the child, was negatively associated with child's socio-emotional development in Bangladesh. That is, increasing the variety of stimulation activities was associated with decreasing odds of child's progress towards socio-emotional development. Further, while assessing the adjusted effect of each stimulation activity separately, similarly to previous study [@alam2021early] this study found that the activity of taking children outside was negatively related to child's development in socio-emotional domain. Playing with children was also found to be negatively associated with socio-emotional development. These findings run contrary to popular belief that the stimulation activities considered should have a positive effect on socio-emotional development. [@alam2021early] in their study offered the explanation that going out with parents or any other caregiver may not be a positive experience for children in a populous country like Bangladesh. There does not seem to be any obvious explanation for the observed negative association between level of stimulation and child's socio-emotional development. Since information regarding caregivers' stimulation acitivites with the child were confined to only 3 days preceding the survey, one cannot be sure that the same stimulation level was maintained for a  long period  of time before the survey. In other words, the observed socio-emotional status of the child cannot be explained entirely by the caregiver stimulation behaviour observed in the 3 days preceding the survey. We conjecture that the observed negative association may be the result of socio-emotionally impaired children being given greater stimulation to overcome their shortcomings. The study did find, however, a positive association between socio-emotional development and the activity singing song with child. In light of these findings one may conclude that the type of activity may be more important in socio-emotional development rather than the number of different types of activities performed. But since MICS data are cross sectional and observational, causality of the relationship between child's socio-emotional development and caregivers' stimulation cannot be established.

## Limitations of the study

There are several limitations of this study. First, the MICS provided only a snapshot
of parent–child interaction during the 3 days preceding the survey and provided information about the types of activities that mothers, fathers or other caregivers engaged in, but not the actual frequency or duration and quality of caregivers' engagement. So, it is not guaranteed that the data accurately depicts the actual situation. Because parenting, child development, and parent–child relationships all develop dynamically.

Second, information on maternal, paternal and other caregivers' engagement at home relied on the same primary caregivers’ self-report, thus allowing for potential bias (recall bias and social desirability bias) in the data.

Third, MICS uses a limited number of specific and presumably universal items to quantify caregiving. Yet, caregivers in different culture may engage in other social-specific forms of caregiving that adequately substitute for specific MICS items. The same caregiving cognition or practice can have the same or different meanings in different contexts, just as different caregiving cognitions or practices can have the same or different meanings in different contexts. Moreover, next to quantitative aspects of caregiving activities, qualitative aspects matter a great deal. Consider playing with child; two mothers could equate in their frequencies
of play, yet one mother might solicit sequences of high-level play that challenge and advance her child’s play skills, whereas another mother might demonstrate low-level play that does not advance her child’s skills. In addition to considering the
form and level of caregiving, it is critical to consider the timing and content of caregiving with respect to children’s ongoing activities.

Another limitation of this study is that we did not control for additional variables that may be potential confounders such as nutritional status of the child. 


## Recommendations

Childhood is a vital period for the formation of human and social capital and is critical in preparing societies for future prosperity, sustainability, and therefore, children's optimal socio-emotional development is a critical component of a country's sustainable development. Supporting early childhood development strengthens human capital architecture, increases economic performance, fosters community development. Parents are the first and principal individuals entrusted with child care and the primary responsibility of developing children to become competent members of their community worldwide. Children thrive when their families provide cognitive and socio-emotional care, which includes imparting information through tutoring and instilling interpersonal competency through socialization. This study investigated the socio-emotional development only in children aged 3-4 years, but the socio-emotional development of children and caregivers' stimulation are matter of long time. To determine the feasibility of achieving the Sustainable Development Goals (SDGs) by 2030 and to obtain an accurate picture of socio-emotional development and the effect of caregiver stimulation on development, execution of cohort study with the specific purpose of assessing the quantity, duration, and quality of caregivers' engagement with the child and observing the child's development is required.


