# Data and Variables

## Data overview and Source


The current analyses were conducted using data from most recent Bangladesh Multiple Indicator Cluster Survey (MICS) 2019, which was conducted by BBS and funded and supervised by UNICEF as part of the worldwide MICS program. The survey collects statistically valid and internationally comparable statistics that are critical for formulating evidence-based policies and programs and tracking progress toward national and global goals. This is a nationally representative sample survey done using a two-stage, stratified cluster sampling approach with the goal of collecting data on women's and children's demographics and numerous health, nutrition, and education-related variables. The primary objective of the Bangladesh MICS 2019 sample design was to generate statistically reliable estimates of the most of of indicators at the national level for urban and rural areas, eight divisions of the country (Barishal, Chattogram, Dhaka, Khulna, Mymensingh, Rajshahi, Rangpur, and Sylhet), and 64 districts.

The sample strata consisted of 64 districts of the country, with enumeration areas (EAs) serving as the primary sampling units and households serving as the secondary sampling units. The sampling frame was constructed using an updated version of Bangladesh's 2011 Census of Population and Housing. In the first stage of sampling, a total of 3,220 EAs were selected from the strata using the probability proportional to size (PPS) approach. In the second stage, a random systematic selection technique was used to choose a sample of 20 houses from each sampled EA. This resulted in a final sample of 64,400 households, roughly 1,000 from each stratum. As the sample is not self-weighting, sample weights are required for analysis [@mics].

The current analysis is performed by extracting relevant information from survey datasets on children under the age of five. The survey collected data with the use of five questionnaires. Among these, data on a child's socio-emotional development were gathered using a "Questionnaire for children under the age of five". The questionnaire for under-5 children was presented to mothers (or caregivers) of all children under the age of five living in each selected household. Mothers (or caregivers) were asked all important questions regarding their children. The working dataset on children under the age of five is then created by merging separate datasets on children and household characteristics. Among these children, data on Early childhood development were obtained on 9445 children aged 3–4 years who formed the study's sample.


## Dependent Variable

The outcome variable of interest is whether or not a child is developing normally in terms of socio-emotional development. The MICS 2019 survey in Bangladesh employed 10-item module for collecting data on four domains ( physical, literacy-numeracy, learning, and socio-emotional) of early childhood development. Three questions (items) with binary response (yes and no) were used to determine whether a child is developmentally on track in the socio-emotional domain. These are: 1. Does child get along well with other children, 2. Does child kick, bite, or hit other children or adults, 3. Does child get distracted easily. Now according to MICS 2019 report, Children are considered to be developmentally on track if any two of the following are true: the child gets along well with other children, the child does not kick, bite, or hit other children and the child does not get distracted easily. However, it does not seem reasonable to consider an aggressive child as socio-emotionally on track when he/she is not distracted and gets along well with others. Similarly an unfriendly child cannot be considered as socio-emotionally on track even if he/she is not aggressive and not distracted. In our opinion, a child is lacking in socio-emotional development if he/she exhibits at least one of the following traits: (a) does not get along well with other children, (b) kicks, bites or hits other children or adults, (c) gets distracted easily. Thus, we create a binary response variable that takes the value 0 if the child showed one or more of the above characteristics and 1 otherwise.


## Independent Variables

### Caregivers' Stimulation

In MICS survey primary caregivers were asked to report on whether mothers, fathers and/or other household member age 15 or over engaged in any of the following six activities with their children in the past 3 days: 

(1) reading books or looking at pictures 
(2) telling stories; 
(3) singing songs 
(4) taking the child outside 
(5) playing with the child 
(6) naming, counting, or drawing with the child

These items reflect a measure of caregivers’ engagement in stimulation to support early childhood development [@bornstein2012cognitive]. Six variables with binary responses were constructed based on caregiver's six stimulation activities. If any of the caregivers (father, mother, or other household member aged 15 or older) engaged in the relevant activity, the response to corresponding variable is "yes" (coded as 1); otherwise, the response is "no" (coded as 0). Then, a summary score was calculated by summing the above six binary variables, which varied from 0 (no caregivers' engagement in any of six stimulation activities) to 6 (caregivers' engagement in all six stimulation activities within the last three days), similarly to how it has been defined and utilized in previous studies as a measure of caregivers' stimulation [@bornstein2012cognitive; @sun2016factors]. Then a categorical variable "Stimulation level" was created by categorizing total number of stimulation activities into 3 groups: "low" (0-1 stimulation activity), "Moderate" (2-3 stimulation activities) and "High" (4-6 stimulation activities).


### Potential Confounders

The following covariates were included to reduce the risk of confounding: sex of child, area of residence (urban or rural), administrative division, household wealth index quintile, father's level of education, mother's level of education, child's disability status, mother's disability status, supervision of child, early childhood education (ECE) programme attendance, child disciplinary actions.

The wealth index variable in the MICS data set was constructed using the first principal component of a group of context-specific assets owned by the household and separated into quintiles: poorest, poor, middle, rich, richest. Caregivers' (father and mother) level of education was categorized into 4 groups: pre-primary or none, primary, secondary, higher secondary or above. Both child's disability status and mother's disability status are binary variable (with levels:  Has functional difficulty,  Has no functional difficulty). ECE attendance is also a binary variable which asks whether a child ever attended any early childhood education programme (such as PRE-SCHOOL/ECD CENTER /NURSERY/KG SCHOOL) with response "yes" or "no". The binary variable 'supervision of child' is constructed from the survey where If a child was left alone at home or in the care of another child under the age of ten for more than an hour in the preceding week, that child was deemed to be under inadequate supervision; otherwise child was considered to be under adequate supervision. 

The categorical variable 'Child disciplinary action' was constructed based on a set of questions asked to mothers or caretakers of children under the age of five years in the MICS 2019 survey. These were the inquiries: whether any of the adult members of the family used any of the following methods to discipline the child during the past month. (1) Took away privileges, forbade something the child liked or did not allow him/her to leave the house; (2) Explained why his (child's) behaviour was wrong; (3) Gave the child something else to do; (4) Shouted, yelled at or screamed at the child; (5) Called the child dumb, lazy or another name like that; (6) Shook the child; (7) Spanked, hit or slapped the child on the bottom with bare hand; (8) Hit the child on the bottom or elsewhere on the body with something like a belt, hairbrush, stick or other hard object; (9) Hit or slapped the child on the face, head or ears; (10) Hit or slapped the child on the hand, arm, or leg; (11) Beat the child up, that is hit him/her over and over as hard as one could.

Responses to each of these questions were binary (yes or no). Child disciplinary action was categorized as 4 groups: "Non-violent" if methods 1-3 had been used; "Psycological Aggression" if methods 4-5 had been used; "Physical Aggression" if methods 6-11 had been used to discipline the child; "None" if none of these methods were used.
